// flow-typed signature: 3c845305774d0571ae092ac5e83e7bb1
// flow-typed version: <<STUB>>/mysql-utilities_v^1.0.13/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mysql-utilities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mysql-utilities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mysql-utilities/example' {
  declare module.exports: any;
}

declare module 'mysql-utilities/utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mysql-utilities/example.js' {
  declare module.exports: $Exports<'mysql-utilities/example'>;
}
declare module 'mysql-utilities/utilities.js' {
  declare module.exports: $Exports<'mysql-utilities/utilities'>;
}
